apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-prod-thanos-extractor

commonLabels:
  app.kubernetes.io/name: data-hub
  app.kubernetes.io/component: argo
  app.kubernetes.io/managed-by: aicoe-data-hub-argocd

resources:
  - ../../base
  - ./membership.yaml

patchesStrategicMerge:
  - deployments/argo-server_patch.yaml
  - deployments/workflow-controller_patch.yaml
